services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm
    volumes:
      - /mnt/data/models/hf:/root/.cache/huggingface
      # Swap the .cmd file below to switch models quickly.
      # Options in this directory: gemma4-12b-awq-single-gpu.cmd, gemma4-12b-awq-pp2.cmd, qwen.cmd, gemma4.cmd
      - ./gemma4-12b-awq-pp2.cmd:/app/args.txt:ro
      - ./entrypoint.sh:/app/entrypoint.sh:ro
    restart: "no"
    privileged: true
    ports:
      - "7777:7777"
    env_file:
      - .env
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - HF_TOKEN=${HF_TOKEN}
      - CUDA_DEVICE_ORDER=PCI_BUS_ID
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
    entrypoint: ["/app/entrypoint.sh"]
    labels:
      - "homepage.group=AI"
      - "homepage.name=vLLM"
      - "homepage.icon=/icons/vllm.png"
      - "homepage.href=http://192.168.254.111:7777"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [
                'GPU-88a93309-9467-dab9-9491-30f298a784f1',
                'GPU-5a6bd876-90f0-e6cf-a89e-ed47392ceb59'
              ]
              capabilities: [ gpu ]

networks:
  proxy:
    external: tr
