Lorbus/Qwen3.6-27B-int4-AutoRound
--tensor-parallel-size 2
--dtype half
--max-model-len 4096
--gpu-memory-utilization 0.85
--kv-cache-dtype fp8
--max-num-seqs 1
--reasoning-parser qwen3
--enable-auto-tool-choice
--tool-call-parser qwen3_xml
--trust-remote-code
--compilation-config.cudagraph_mode none
--disable-custom-all-reduce
--host 0.0.0.0
--port 7777