{
 "title": "System Telemetry - Enhanced (Nvitop)",
 "description": "Grafana Dashboard built by `nvitop-exporter`.",
 "tags": [
  "nvitop",
  "nvitop-exporter",
  "prometheus",
  "nvidia",
  "gpu",
  "gpu process",
  "gpu monitoring"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "host_cpu_percent_Percentage{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} CPU"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 18, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_utilization_Percentage{hostname=~\"$hostname\"}",
     "legendFormat": "{{devicename}} [Slot {{index}}]"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "gauge",
   "gridPos": { "h": 18, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_memory_percent_Percentage{hostname=~\"$hostname\"}",
     "legendFormat": "{{devicename}} [Slot {{index}}]"
    }
   ]
  },
  {
   "title": "Host Virtual Memory",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "host_virtual_memory_percent_Percentage{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} MEM"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Number of GPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(group by(uuid) (process_gpu_memory_MiB{hostname=~\"$hostname\", username=~\"$username\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(gpu_memory_total_MiB{hostname=~\"$hostname\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Running GPU Processes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by(hostname, index) (process_gpu_memory_MiB{hostname=~\"$hostname\", username=~\"$username\"})",
     "legendFormat": "{{devicename}} [Slot {{index}}]"
    }
   ]
  },
  {
   "title": "Number of Running GPU Processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by(hostname) (count by(hostname, pid) (process_info_info{hostname=~\"$hostname\", username=~\"$username\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Processes",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "process_cpu_percent_Percentage{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_rss_memory_MiB{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_gpu_memory_MiB{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_gpu_sm_utilization_Percentage{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_gpu_memory_utilization_Percentage{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_gpu_encoder_utilization_Percentage{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_gpu_decoder_utilization_Percentage{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_running_time_Second{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_info_info{hostname=~\"$hostname\", username=~\"$username\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "host_virtual_memory_total_MiB{hostname=~\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu_memory_total_MiB{hostname!~\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "host_cpu_percent_Percentage{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "host_load_average_1m_Percentage{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} (1m)"
    },
    {
     "expr": "host_load_average_5m_Percentage{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} (5m)"
    },
    {
     "expr": "host_load_average_15m_Percentage{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} (15m)"
    }
   ]
  },
  {
   "title": "Host Virtual Memory",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "host_virtual_memory_used_MiB{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Host Swap Memory",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "host_swap_memory_used_MiB{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "System I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Host Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "sum by(hostname) (rate(host_net_io_rx_data_MiB{hostname=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "{{hostname}} RX"
    },
    {
     "expr": "sum by(hostname) (rate(host_net_io_tx_data_MiB{hostname=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "{{hostname}} TX"
    }
   ]
  },
  {
   "title": "Host Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "sum by(hostname) (rate(host_disk_io_read_data_MiB{hostname=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "{{hostname}} Read"
    },
    {
     "expr": "sum by(hostname) (rate(host_disk_io_write_data_MiB{hostname=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "{{hostname}} Write"
    }
   ]
  },
  { "title": "Device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpu_utilization_Percentage{hostname=~\"$hostname\"}",
     "legendFormat": "{{devicename}} [Slot {{index}}]"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "gpu_memory_used_MiB{hostname=~\"$hostname\"}",
     "legendFormat": "{{devicename}} [Slot {{index}}]"
    }
   ]
  },
  {
   "title": "GPU PCIe RX Throughput",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "gpu_pcie_rx_throughput_MiBps{hostname=~\"$hostname\"}",
     "legendFormat": "{{devicename}} [Slot {{index}}]"
    }
   ]
  },
  {
   "title": "GPU PCIe TX Throughput",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "gpu_pcie_tx_throughput_MiBps{hostname=~\"$hostname\"}",
     "legendFormat": "{{devicename}} [Slot {{index}}]"
    }
   ]
  },
  {
   "title": "GPU NVLink RX Throughput",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "gpu_nvlink_total_rx_throughput_MiBps{hostname=~\"$hostname\"}",
     "legendFormat": "{{devicename}} [Slot {{index}}]"
    }
   ]
  },
  {
   "title": "GPU NVLink TX Throughput",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "gpu_nvlink_total_tx_throughput_MiBps{hostname=~\"$hostname\"}",
     "legendFormat": "{{devicename}} [Slot {{index}}]"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "gpu_power_usage_W{hostname=~\"$hostname\"}",
     "legendFormat": "{{devicename}} [Slot {{index}}]"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "gpu_temperature_C{hostname=~\"$hostname\"}",
     "legendFormat": "{{devicename}} [Slot {{index}}]"
    }
   ]
  }
 ]
}