services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    ports:
      - "13378:80"
    environment:
      - TZ=UTC # Change this to your local timezone if needed
    volumes:
      - ./config:/config
      - ./metadata:/metadata
      - /mnt/storage/media/audiobooks:/audiobooks
    restart: unless-stopped
    networks:
      - default
      - proxy
    labels:
      - "wud.watch.digest=true"
      - "homepage.group=Media Automation"
      - "homepage.name=Audiobookshelf"
      - "homepage.icon=audiobookshelf.png"
      - "homepage.href=http://192.168.254.111:13378"
      # - "homepage.description=Audiobooks & Podcasts"
      - "homepage.widget.type=audiobookshelf"
      - "homepage.widget.url=http://192.168.254.111:13378"
      - "homepage.target=_self"
      - "homepage.widget.key=${HOMEPAGE_VAR_AUDIOBOOKSHELF_KEY}"
      - "homepage.widget.showStats=true"

  # abs-tract is primarily used to sync an Audible library to Audiobookshelf.
  # Since you mentioned you might have only needed it once for migration, 
  # it is not required for Audiobookshelf to function normally.
  # You can leave it commented out if you no longer need to sync from Audible.
#  abs-tract:
#    image: arranhs/abs-tract
#    build:
#     context: .
#    container_name: abs-tract
#    ports:
#     - "6666:5555"
#    restart: unless-stopped
#
networks:
  proxy:
    external: true
