services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    ports:
      - "13378:80"
    environment:
      - TZ=UTC # Change this to your local timezone if needed
    volumes:
      - ./config:/config
      - ./metadata:/metadata
      - /mnt/storage/media/audiobooks:/audiobooks
    restart: unless-stopped
    networks:
      - default
      - proxy
    labels:
      - "wud.watch.digest=true"
      # - "homepage.group=Media Automation"
      # - "homepage.id=audiobookshelf-card"
      # - "homepage.name=Audiobookshelf"
      # - "homepage.icon=audiobookshelf.png"
      # - "homepage.target=_self"
      # - "homepage.href=http://192.168.254.111:13378"
      # - "homepage.description=Audiobooks & Podcasts"
      # - "homepage.widget.type=audiobookshelf"
      # - "homepage.widget.url=http://192.168.254.111:13378"
      # - "homepage.widget.key=${HOMEPAGE_VAR_AUDIOBOOKSHELF_KEY}"
      # - "homepage.widget.showStats=true"
  # abs-tract is primarily used to sync an Audible library to Audiobookshelf.
  abs-tract:
    image: arranhs/abs-tract
    build:
     context: .
    container_name: abs-tract
    ports:
     - "6666:5555"
    restart: unless-stopped

  # libation downloads your Audible library to /mnt/storage/media/audiobooks
  libation:
    image: rmcrackan/libation:latest
    container_name: libation
    user: "1000:1000"
    volumes:
      - ./libation_config:/config
      - /mnt/storage/media/audiobooks:/data
    environment:
      - TZ=America/New_York
      - SLEEP_TIME=1440m
    restart: unless-stopped

networks:
  proxy:
    external: true
