services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    hostname: plex-server
    ports:
      - "32400:32400"
    networks:
      - default
      - proxy
    labels:
        - "homepage.group=Media Automation"
        - "homepage.name=Plex"
        - "homepage.icon=plex.png"
        - "homepage.href=http://192.168.254.111:32400/web"
        - "homepage.description=Media Server"
        - "homepage.widget.type=plex"
        - "homepage.widget.url=http://192.168.254.111:32400"
        - "homepage.target=_self"
        - "homepage.widget.key=${PLEX_TOKEN}"
        - 'homepage.widget.fields=["streams", "movies", "tv"]'
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /mnt/data/media_cache/plex/config:/config
      # Mapping your existing media pool
      - /mnt/storage/media:/media
      # Optional: Transcode to RAM (saves SSD wear). Requires enough RAM (8GB+ system).
      # If you have low RAM, remove this line.
      - /dev/shm:/transcode
    restart: unless-stopped

networks:
  proxy:
    external: true
