services:
    # --- 1. DOWNLOADER & VPN (All-in-one) ---
    delugevpn:
        image: binhex/arch-delugevpn
        mem_swappiness: 0
        deploy:
          resources:
            limits:
              memory: 1gb
              cpus: '0.5'
        container_name: delugevpn
        privileged: true
        cap_add:
            - NET_ADMIN
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        ports:
            - "8112:8112" # Web UI
            - "58846:58846" # Daemon Port
            - "8118:8118" # Privoxy
        environment:
            - VPN_ENABLED=yes
            - VPN_PROV=custom
            - VPN_CLIENT=wireguard
            - STRICT_PORT_FORWARD=yes
            - ENABLE_PRIVOXY=yes
            - LAN_NETWORK=192.168.254.0/24,172.16.0.0/12,172.30.0.0/16,100.64.0.0/10
            - NAME_SERVERS=1.1.1.1,1.0.0.1
            - DELUGE_DAEMON_LOG_LEVEL=info
            - WEBUI_PORT=8112
            - UMASK=000
            - PUID=1000
            - PGID=1000
            - TZ=America/Los_Angeles
        volumes:
            - /mnt/storage/media:/data
            - ./config/deluge:/config
            - ./config/vpn:/config/wireguard
        restart: unless-stopped
        networks:
            - default
            - proxy
        labels:
            - "wud.watch.digest=true"
        # - "homepage.group=Media Automation"
        # - "homepage.name=Deluge"
        # - "homepage.icon=deluge.png"
        # - "homepage.href=http://192.168.254.111:8112"
      # - "homepage.description=Downloads (VPN)"
        # - "homepage.widget.type=deluge"
        # - "homepage.widget.url=http://delugevpn:8112"
        # - "homepage.widget.password=deluge"

    # --- 2. ARRRRRRRR ---
    radarr:
        image: linuxserver/radarr:latest
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Los_Angeles
        ports:
            - "7878:7878"
        volumes:
            - ./config/radarr:/config
            - /mnt/storage/media:/data
        restart: unless-stopped
        networks:
            - default
            - proxy
        labels:
            - "wud.watch.digest=true"
            - "auto.arr=true"
            - "auto.arr.port=7878"
        # - "homepage.group=Media Automation"
            - "homepage.name=Radarr"
            - "homepage.icon=radarr.png"
            - "homepage.href=http://192.168.254.111:7878"
      # - "homepage.description=Movies"
            - "homepage.widget.type=radarr"
            - "homepage.widget.url=http://radarr:7878"
            - "homepage.widget.key=${HOMEPAGE_VAR_RADARR_KEY}"
            - "homepage.widget.showStats=true"

    sonarr:
        image: linuxserver/sonarr:latest
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Los_Angeles
        ports:
            - "8989:8989"
        volumes:
            - ./config/sonarr:/config
            - /mnt/storage/media:/data
        restart: unless-stopped
        networks:
            - default
            - proxy
        labels:
            - "wud.watch.digest=true"
            - "auto.arr=true"
            - "auto.arr.port=8989"
        # - "homepage.group=Media Automation"
            - "homepage.name=Sonarr"
            - "homepage.icon=sonarr.png"
            - "homepage.href=http://192.168.254.111:8989"
      # - "homepage.description=TV Shows"
            - "homepage.widget.type=sonarr"
            - "homepage.widget.url=http://sonarr:8989"
            - "homepage.widget.key=${HOMEPAGE_VAR_SONARR_KEY}"
            - "homepage.widget.showStats=true"

    prowlarr:
        image: ghcr.io/linuxserver/prowlarr:latest
        container_name: prowlarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Los_Angeles
        ports:
            - "9696:9696"
        volumes:
            - ./config/prowlarr:/config
        restart: unless-stopped
        networks:
            - default
            - proxy
        labels:
            - "wud.watch.digest=true"
            - "auto.arr=true"
            - "auto.arr.port=9696"
        # - "homepage.group=Media Automation"
            - "homepage.name=Prowlarr"
            - "homepage.icon=prowlarr.png"
            - "homepage.href=http://192.168.254.111:9696"
      # - "homepage.description=Indexer Manager"
            - "homepage.widget.type=prowlarr"
            - "homepage.widget.url=http://192.168.254.111:9696"
            - "homepage.target=_self"
            - "homepage.widget.key=${HOMEPAGE_VAR_PROWLARR_KEY}"
            - "homepage.widget.showStats=true"

    flaresolverr:
        image: flaresolverr/flaresolverr:latest
        container_name: flaresolverr
        labels:
            - "wud.watch.digest=true"
        environment:
            - LOG_LEVEL=info
            - TZ=America/Los_Angeles
        ports:
            - "8191:8191"
        restart: unless-stopped

networks:
  proxy:
    external: true
