services:
  # llama-swap - Manages llama-server processes for hot-swapping
  llama-swap:
    image: ghcr.io/mostlygeek/llama-swap:unified-cuda
    container_name: llama-swap
    user: root
    restart: unless-stopped
    ports:
      - "5800:5800"
      - "8082:8080"
    volumes:
      - /mnt/data/models/llm:/mnt/data/models/llm
      - ./configs:/app/configs:ro
    environment:
      - LLAMA_CACHE=/mnt/data/models/llm
      - HF_HOME=/mnt/data/models/llm
      - NVIDIA_DRIVER_CAPABILITIES=all
#      - CUDA_VISIBLE_DEVICES=all
#      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=${GPU_SLOT_1:?GPU_SLOT_3_NOT_SET},${GPU_SLOT_3:?GPU_SLOT_3_NOT_SET}
    command: ["--config-dir", "/app/configs", "--listen", "0.0.0.0:8080"]
    working_dir: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [
#                '0','1','2'
                  '${GPU_SLOT_1:?GPU_SLOT_1_NOT_SET}',
                  '${GPU_SLOT_3:?GPU_SLOT_3_NOT_SET}'
              ]
              capabilities: [ all ]
    networks:
      - default
      - proxy
    #    labels:
    #        - "homepage.group=AI"
    #        - "homepage.id=llama-swap-card"
    #        - "homepage.name=Llama Swap"
    #        - "homepage.icon=/icons/llama.png"
    #        - "homepage.href=http://192.168.254.111:8082"
    #        - "homepage.target=_self"
    #        - "homepage.description=LLM Hot-Swapper & UI"

volumes:
  litellm_db_data:

networks:
  proxy:
    external: true
