"""baseline schema

Revision ID: 29cb08ebc97f
Revises: 
Create Date: 2026-09-14 01:00:12.417711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29cb08ebc97f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_names',
    sa.Column('entity_ref', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('npi', sa.String(length=20), nullable=True),
    sa.Column('display', sa.Text(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('entity_ref')
    )
    op.create_table('job_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('counts', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_run_provider'), 'job_run', ['provider'], unique=False)
    op.create_table('oauth_tokens',
    sa.Column('patient_id', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('access_token', sa.String(length=2000), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('expires_in', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('id_token', sa.Text(), nullable=True),
    sa.Column('obtained_at', sa.DateTime(), nullable=False),
    sa.Column('refresh_token_expires_in', sa.Integer(), nullable=False),
    sa.Column('last_eob_fetch', sa.DateTime(), nullable=True),
    sa.Column('last_claim_fetch', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('patient_id', 'provider')
    )
    op.create_table('patients',
    sa.Column('patient_id', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('entity_ref', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('patient_id', 'provider')
    )
    op.create_table('pkce_verifiers',
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('verifier', sa.String(length=200), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('provider')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pkce_verifiers')
    op.drop_table('patients')
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_job_run_provider'), table_name='job_run')
    op.drop_table('job_run')
    op.drop_table('entity_names')
    # ### end Alembic commands ###
