services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    init: true
    networks:
      - homepage_default      # Keep its own network
      - immich_net            # Connect to Immich
      - arr_net               # Connect to new Arr stack
      - proxy
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    volumes:
      - ./config:/app/config
      - ./public/icons:/app/public/icons
      - ./public/images:/app/public/images
#      - ./public/background.png:/app/public/background.png
      - ./public/snapraid.json:/app/public/snapraid.json
      - /var/run/docker.sock:/var/run/docker.sock:ro # Optional: For Docker stats
      - /var/snapraid.content:/app/data/snapraid.content:ro
    environment:
      PUID: 1000
      PGID: 987
      # "*" tells Homepage to accept connections from ANY IP or Hostname
      HOMEPAGE_ALLOWED_HOSTS: "*"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`home.lan`) || Host(`homepage.home.lan`)"
      - "traefik.http.routers.homepage.entrypoints=web"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
    restart: unless-stopped

  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    pid: host
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - GLANCES_OPT=-w -B 0.0.0.0
    ports:
      - "61208:61208"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, video, utility]
    networks:
      - homepage_default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glances.rule=Host(`glances.home.lan`)"
      - "traefik.http.routers.glances.entrypoints=web"
      - "traefik.http.services.glances.loadbalancer.server.port=61208"
      - "homepage.group=System"
      - "homepage.name=Glances"
      - "homepage.icon=glances.png"
      - "homepage.href=http://192.168.254.111:61208"
      - "homepage.description=System Monitoring"

networks:
  proxy:
    external: true
  homepage_default:
  immich_net:
    name: immich_default           # This MUST match the name in your terminal output
    external: true
  arr_net:
    name: arr-stack_default
    external: true
