services:
  llama-cpp:
    image: llama-cpp-local:server-cuda
#    image: ghcr.io/ggml-org/llama.cpp:server-cuda-june-08
    container_name: llama-cpp
    restart: unless-stopped
    ipc: host # CRITICAL: Gives NCCL access to shared memory segments for P2P/AllReduce
    ports:
      - "8082:8080"
    volumes:
      - /mnt/data/models/llm:/mnt/data/models/llm
      - ./models.ini:/app/models.ini:ro
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - LD_LIBRARY_PATH=/app:/usr/local/cuda/lib64
      - NCCL_DEBUG=WARN
      # If NCCL still chokes on networking setups, uncomment the line below to force it to use local P2P:
      # - NCCL_NET_PLUGIN=none
    # Start in router mode using the models.ini preset
    command: ["--models-preset", "/app/models.ini",
              "--port", "8080",
              "--host", "0.0.0.0",
    ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/models"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [
                'GPU-88a93309-9467-dab9-9491-30f298a784f1', # RTX 3060 12GB
                'GPU-5a6bd876-90f0-e6cf-a89e-ed47392ceb59'  # RTX 3060 12GB
              ]
              capabilities: [ gpu ]
    networks:
      - default
      - proxy
    labels:
      - "wud.watch.digest=true"
      - "homepage.group=AI"
      - "homepage.name=Llama CPP Native"
      - "homepage.icon=/icons/llama.png"
      - "homepage.href=http://192.168.254.111:8082"

networks:
  proxy:
    external: true
