;version = 1

[*]
host = 0.0.0.0
flash-attn = true
n-gpu-layers = 99
split-mode = layer
tensor-split = 1,1
;fit = off
reasoning = on

[Qwen3.6-27B]
model = /mnt/data/models/llm/Qwen3.6/27B-MTB/Qwen3.6-27B-Q4_K_S.gguf
mmproj = /mnt/data/models/llm/Qwen3.6/27B-MTB/mmproj-BF16.gguf
split-mode = tensor
n-gpu-layers = 99
parallel = 1
jinja = true
ctx-size = 65536
temp = 0.6
presence-penalty = 0.0
chat-template-kwargs = {"preserve_thinking":false}

[Gemma-4-12B-MTP]
model = /mnt/data/models/llm/Gemma/12B/gemma-4-12B-it-qat-UD-Q4_K_XL.gguf
mmproj = /mnt/data/models/llm/Gemma/12B/mmproj-BF16.gguf
model-draft = /mnt/data/models/llm/Gemma/12B/mtp-gemma-4-12b-it.gguf
spec-type = draft-mtp
spec-draft-n-max = 2
chat-template-kwargs = {"enable_thinking": true}
jinja = true
parallel = 2
ctx-size = 262144
temp = 1.0
top-p = 0.95
top-k = 64
min-p = 0.01
n-predict = 2048

[Gemma4-26B-A4B-QAT]
model = /mnt/data/models/llm/Gemma/26B-A4B/gemma-4-26B-A4B-it-qat-UD-Q4_K_XL.gguf
mmproj = /mnt/data/models/llm/Gemma/26B-A4B/mmproj-BF16.gguf
model-draft = /mnt/data/models/llm/Gemma/26B-A4B/mtp-gemma-4-26B-A4B-it.gguf
spec-type = draft-mtp
spec-draft-n-max = 2
chat-template-kwargs = {"enable_thinking": true}
jinja = true
parallel = 1
ctx-size = 65536
temp = 1.0
top-p = 0.95
top-k = 64
min-p = 0.01
repeat-penalty = 1.0
n-predict = 2048

[Gemma4-31B-QAT]
model = /mnt/data/models/llm/Gemma/31B/gemma-4-31B-it-qat-UD-Q4_K_XL.gguf
mmproj = /mnt/data/models/llm/Gemma/31B/mmproj-BF16.gguf
model-draft = /mnt/data/models/llm/Gemma/31B/mtp-gemma-4-31B-it.gguf
spec-type = draft-mtp
spec-draft-n-max = 2
chat-template-kwargs = {"enable_thinking": true}
jinja = true
parallel = 1
ctx-size = 65536
temp = 1.0
top-p = 0.95
top-k = 64
min-p = 0.01
repeat-penalty = 1.0
n-predict = 2048
