version = 1

[*]
# Global defaults for all models on PC2
host = 0.0.0.0
flash-attn = on
parallel = 1
fit = on
tensor-split = 12,12
kv-unified = off
cache-type-k = q4_0
cache-type-v = q4_0
n-gpu-layers = 999
ctx-size = 32768

[Gemma-4-26B]
model = /mnt/data/models/llm/Gemma/26B-A4B/gemma-4-26B-A4B-it-UD-IQ4_NL.gguf
mmproj = /mnt/data/models/llm/Gemma/26B-A4B/mmproj-BF16.gguf
chat-template-kwargs = {"enable_thinking":true}


[Gemma-4-31B]
model = /mnt/data/models/llm/Gemma/gemma-4-31B-it-IQ4_NL.gguf
mmproj = /mnt/data/models/llm/Gemma/31B/mmproj-BF16.gguf
chat-template-kwargs = {"enable_thinking":true}



[Qwen3.6-27B]
model = /mnt/data/models/llm/Qwen3.6/27B-MTB/Qwen3.6-27B-IQ4_NL.gguf
mmproj = /mnt/data/models/llm/Qwen3.6/27B-MTB/mmproj-BF16.gguf
spec-type = draft-mtp
spec-draft-n-max = 1
parallel = 1
temp = 0.7
top-p = 0.8
top-k = 20
min-p = 0.00
reasoning = off
ctx-size = 65536
;no-mmap = on

;[Qwen3.6-27B]
;model = /mnt/data/models/llm/Qwen3.6/27B/Qwen3.6-27B-UD-Q4_K_XL.gguf
;mmproj = /mnt/data/models/llm/Qwen3.6/27B/mmproj-BF16.gguf
;parallel = 2
;cache-prompt = off
;temp = 0.7
;top-p = 0.8
;top-k = 20
;min-p = 0.00
;reasoning = off
;ctx-size = 65536
;
;
;[Qwen3.6-27B-MTB]
;hf = unsloth/Qwen3.6-27B-MTP-GGUF
;hf-file = Qwen3.6-27B-UD-Q4_K_XL.gguf
;temp = 0.7
;top-p = 0.8
;top-k = 20
;min-p = 0.00
;reasoning = off
;ctx-size = 4096
;fit = on


;tensor-split = 9,15

;[Qwen3.6-27B-Thinking]
;model = /mnt/data/models/llm/Qwen3.6/27B/Qwen3.6-27B-UD-Q4_K_XL.gguf
;mmproj = /mnt/data/models/llm/Qwen3.6/27B/mmproj-BF16.gguf
;temp = 1.0
;top-p = 0.95
;top-k = 20
;min-p = 0.00
;reasoning = on
;ctx-size = 65536
;batch-size = 2048
;ubatch-size = 1024
;;no-mmap = on
