apiVersion: 1

datasources:
  - name: Prometheus-Host
    uid: bfmz2d8egix34a
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: haos
    uid: cfm7mlu97jim8c
    type: influxdb
    access: proxy
    url: http://192.168.254.22:8086
    isDefault: false
    editable: false
    jsonData:
      dbName: haos
      httpMethod: POST

  - name: telemetry
    uid: afmz2jwj2mkn4e
    type: influxdb
    access: proxy
    url: http://192.168.254.22:8086
    isDefault: false
    editable: false
    jsonData:
      dbName: telemetry
      httpMethod: POST
