apiVersion: 1

datasources:
  - name: InfluxDB
    uid: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      version: Flux
      organization: home
    secureJsonData:
      token: telemetry_token_xK9mP2vL7nQ4wR8jF3hY6bT1cA5dS0eU

  - name: Prometheus
    uid: nvitop-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false
