services:
  frigate:
    container_name: frigate
    privileged: false # Keep disabled to enforce GPU device constraints
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "4gb" # Sufficient for ~4-6 1080p cameras. Increase if you see bus errors.
    runtime: nvidia
    env_file:
      - .env
      - ../genai.env
    environment:
      - NVIDIA_VISIBLE_DEVICES=${GPU_3050:?GPU_3050_UUID_NOT_SET}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - CUDA_VISIBLE_DEVICES=${GPU_3050:?GPU_3050_UUID_NOT_SET}
      - FFMPEG_DISABLE_GAMMA_EQUALIZER=true
      - LIBVA_DRIVER_NAME=nvidia
      - OPENAI_BASE_URL=http://gateway:4000/v1
      - OPENAI_API_KEY=${FRIGATE_GENAI_API_KEY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /mnt/disk5/frigate_media:/media/frigate
#      - /mnt/data/media_cache/frigate:/media/frigate
      - /mnt/data/models/frigate-detectors:/models
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
    deploy:
      resources:
        limits:
          memory: 4gb
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["all"]  # MUST expose all device ids in order for hwaccel to work
#              device_ids: ['GPU-f1690852-7dc1-2557-d0f9-93cd6b19b877']
#              device_ids: ["${GPU_3050:?GPU_3050_UUID_NOT_SET}"]
              capabilities: [all]
    networks:
      - default
      - proxy
    labels:
      - "wud.watch.digest=true"
      - "homepage.group=Home Ops"
      - "homepage.name=Frigate"
      - "homepage.icon=frigate.png"
      - "homepage.href=http://192.168.254.111:5000"
      - "homepage.target=_self"
#      - "homepage.description=NVR & Object Detection"
#      - "homepage.widget.type=frigate"
#      - "homepage.widget.url=http://frigate:5000"
#      - 'homepage.widget.mappings=[{"field": "detectors.nvidia.inference_speed", "label": "Inf. Speed", "suffix": "ms"}, {"field": "gpu_usages[\"NVIDIA GeForce RTX 3050\"].mem", "label": "GPU Mem"}]'


networks:
  proxy:
    external: true
