"""baseline schema

Revision ID: 79e9b6bebc7e
Revises: 
Create Date: 2026-09-14 01:00:12.476176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e9b6bebc7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_submission',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('claim_type', sa.Text(), nullable=True),
    sa.Column('use', sa.Text(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('billable_period_start', sa.Date(), nullable=True),
    sa.Column('billable_period_end', sa.Date(), nullable=True),
    sa.Column('patient_ref', sa.Text(), nullable=True),
    sa.Column('provider_ref', sa.Text(), nullable=True),
    sa.Column('insurer_ref', sa.Text(), nullable=True),
    sa.Column('priority', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('total_currency', sa.String(length=3), nullable=True),
    sa.Column('submission_origin', sa.String(length=20), nullable=False),
    sa.Column('is_out_of_network', sa.Boolean(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('claim_number', sa.Text(), nullable=True),
    sa.Column('claim_adjustment_key', sa.Text(), nullable=True),
    sa.Column('sub_type_code', sa.String(length=100), nullable=True),
    sa.Column('sub_type_display', sa.Text(), nullable=True),
    sa.Column('payee_type', sa.String(length=50), nullable=True),
    sa.Column('payee_ref', sa.Text(), nullable=True),
    sa.Column('coverage_ref', sa.Text(), nullable=True),
    sa.Column('preauth_refs', sa.Text(), nullable=True),
    sa.Column('prescription_ref', sa.Text(), nullable=True),
    sa.Column('priority_display', sa.Text(), nullable=True),
    sa.Column('adjudication_date', sa.Date(), nullable=True),
    sa.Column('adjudication_status_code', sa.String(length=50), nullable=True),
    sa.Column('action_date', sa.Date(), nullable=True),
    sa.Column('action_type_code', sa.String(length=50), nullable=True),
    sa.Column('adjustment_number', sa.Text(), nullable=True),
    sa.Column('claim_class_code', sa.String(length=50), nullable=True),
    sa.Column('denial_reason_code', sa.String(length=50), nullable=True),
    sa.Column('line_status_code', sa.String(length=50), nullable=True),
    sa.Column('line_status_display', sa.Text(), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('system_of_record_code', sa.String(length=50), nullable=True),
    sa.Column('discharge_status_code', sa.String(length=50), nullable=True),
    sa.Column('document_control_number', sa.Text(), nullable=True),
    sa.Column('external_load_code', sa.String(length=50), nullable=True),
    sa.Column('in_patient', sa.String(length=10), nullable=True),
    sa.Column('length_of_stay', sa.Integer(), nullable=True),
    sa.Column('network_identifier_code', sa.String(length=50), nullable=True),
    sa.Column('place_of_service_code', sa.String(length=50), nullable=True),
    sa.Column('place_of_service_display', sa.Text(), nullable=True),
    sa.Column('pps_code', sa.String(length=50), nullable=True),
    sa.Column('source_billing_provider_id', sa.Text(), nullable=True),
    sa.Column('source_npi', sa.String(length=20), nullable=True),
    sa.Column('total_diag_code_count', sa.Integer(), nullable=True),
    sa.Column('total_paid_amount', sa.Float(), nullable=True),
    sa.Column('master_consumer_id', sa.Text(), nullable=True),
    sa.Column('mbr_key', sa.Text(), nullable=True),
    sa.Column('ipt_facility_number', sa.Text(), nullable=True),
    sa.Column('ipt_home_code', sa.String(length=50), nullable=True),
    sa.Column('point_of_origin_code', sa.String(length=50), nullable=True),
    sa.Column('priority_admit_type_code', sa.String(length=50), nullable=True),
    sa.Column('dispensed_brand_generic_code', sa.String(length=50), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_names',
    sa.Column('entity_ref', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('npi', sa.String(length=20), nullable=True),
    sa.Column('display', sa.Text(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('entity_ref')
    )
    op.create_table('eob',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('claim_number', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('claim_type', sa.Text(), nullable=True),
    sa.Column('sub_type', sa.Text(), nullable=True),
    sa.Column('use', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('disposition', sa.Text(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('claim_received_date', sa.Date(), nullable=True),
    sa.Column('billable_period_start', sa.Date(), nullable=True),
    sa.Column('billable_period_end', sa.Date(), nullable=True),
    sa.Column('patient_ref', sa.Text(), nullable=True),
    sa.Column('provider_ref', sa.Text(), nullable=True),
    sa.Column('insurer_payer_id', sa.Text(), nullable=True),
    sa.Column('coverage_ref', sa.Text(), nullable=True),
    sa.Column('payee_type', sa.Text(), nullable=True),
    sa.Column('payee_ref', sa.Text(), nullable=True),
    sa.Column('submission_origin', sa.String(length=20), nullable=False),
    sa.Column('is_out_of_network', sa.Boolean(), nullable=False),
    sa.Column('claim_adjustment_key', sa.Text(), nullable=True),
    sa.Column('payment_amount', sa.Float(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_type', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('insurer_ref', sa.Text(), nullable=True),
    sa.Column('payment_currency', sa.String(length=3), nullable=True),
    sa.Column('payment_adjustment_code', sa.String(length=100), nullable=True),
    sa.Column('payment_adjustment_display', sa.Text(), nullable=True),
    sa.Column('preauth_refs', sa.Text(), nullable=True),
    sa.Column('payer_display', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_claim_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_submission_id', sa.String(length=200), nullable=True),
    sa.Column('patient_id', sa.String(length=200), nullable=True),
    sa.Column('claim_number', sa.Text(), nullable=True),
    sa.Column('provider_ref', sa.String(length=255), nullable=True),
    sa.Column('provider_npi', sa.String(length=20), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('cpt_codes', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('matched_eob_id', sa.Text(), nullable=True),
    sa.Column('matched_claim_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_tokens',
    sa.Column('patient_id', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('access_token', sa.String(length=2000), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('expires_in', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('id_token', sa.Text(), nullable=True),
    sa.Column('obtained_at', sa.DateTime(), nullable=False),
    sa.Column('refresh_token_expires_in', sa.Integer(), nullable=False),
    sa.Column('last_eob_fetch', sa.DateTime(), nullable=True),
    sa.Column('last_claim_fetch', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('patient_id', 'provider')
    )
    op.create_table('patients',
    sa.Column('patient_id', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('entity_ref', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('patient_id', 'provider')
    )
    op.create_table('claim_care_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('provider_ref', sa.Text(), nullable=True),
    sa.Column('role_code', sa.String(length=20), nullable=True),
    sa.Column('role_display', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claim_submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_diagnosis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('icd_code', sa.String(length=15), nullable=True),
    sa.Column('icd_display', sa.Text(), nullable=True),
    sa.Column('diagnosis_type', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claim_submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_identifier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Text(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('system', sa.Text(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('use', sa.String(length=20), nullable=True),
    sa.Column('type_code', sa.String(length=100), nullable=True),
    sa.Column('type_display', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claim_submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('hcpcs_code', sa.String(length=10), nullable=True),
    sa.Column('hcpcs_display', sa.Text(), nullable=True),
    sa.Column('modifier_codes', sa.String(length=100), nullable=True),
    sa.Column('serviced_date', sa.Date(), nullable=True),
    sa.Column('serviced_period_start', sa.Date(), nullable=True),
    sa.Column('serviced_period_end', sa.Date(), nullable=True),
    sa.Column('location_code', sa.String(length=10), nullable=True),
    sa.Column('location_display', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('net_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claim_submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eob_adjudication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eob_id', sa.Text(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('category_code', sa.String(length=100), nullable=True),
    sa.Column('category_display', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('value_units', sa.Integer(), nullable=True),
    sa.Column('reason_code', sa.String(length=100), nullable=True),
    sa.Column('reason_display', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['eob_id'], ['eob.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eob_care_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eob_id', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('provider_ref', sa.Text(), nullable=True),
    sa.Column('role_code', sa.String(length=20), nullable=True),
    sa.Column('role_display', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['eob_id'], ['eob.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eob_diagnosis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eob_id', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('icd_code', sa.String(length=15), nullable=True),
    sa.Column('icd_display', sa.Text(), nullable=True),
    sa.Column('diagnosis_type', sa.String(length=200), nullable=True),
    sa.Column('on_admission', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['eob_id'], ['eob.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eob_identifier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eob_id', sa.Text(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('system', sa.Text(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('use', sa.String(length=20), nullable=True),
    sa.Column('type_code', sa.String(length=100), nullable=True),
    sa.Column('type_display', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['eob_id'], ['eob.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eob_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eob_id', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('hcpcs_code', sa.String(length=10), nullable=True),
    sa.Column('hcpcs_display', sa.Text(), nullable=True),
    sa.Column('modifier_codes', sa.String(length=100), nullable=True),
    sa.Column('serviced_date', sa.Date(), nullable=True),
    sa.Column('serviced_period_start', sa.Date(), nullable=True),
    sa.Column('serviced_period_end', sa.Date(), nullable=True),
    sa.Column('location_code', sa.String(length=10), nullable=True),
    sa.Column('location_display', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('net_amount', sa.Float(), nullable=True),
    sa.Column('submitted_amount', sa.Float(), nullable=True),
    sa.Column('allowed_amount', sa.Float(), nullable=True),
    sa.Column('paid_provider', sa.Float(), nullable=True),
    sa.Column('paid_patient', sa.Float(), nullable=True),
    sa.Column('deductible', sa.Float(), nullable=True),
    sa.Column('coinsurance', sa.Float(), nullable=True),
    sa.Column('copay', sa.Float(), nullable=True),
    sa.Column('noncovered', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('member_liability', sa.Float(), nullable=True),
    sa.Column('allowed_units', sa.Integer(), nullable=True),
    sa.Column('adjustment_reason', sa.Text(), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['eob_id'], ['eob.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eob_procedure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eob_id', sa.Text(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('service_sequence', sa.Integer(), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('code_code', sa.String(length=100), nullable=True),
    sa.Column('code_display', sa.Text(), nullable=True),
    sa.Column('type_code', sa.String(length=100), nullable=True),
    sa.Column('type_display', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['eob_id'], ['eob.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eob_supporting_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eob_id', sa.Text(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('category_code', sa.String(length=100), nullable=True),
    sa.Column('category_display', sa.Text(), nullable=True),
    sa.Column('code_code', sa.String(length=100), nullable=True),
    sa.Column('code_display', sa.Text(), nullable=True),
    sa.Column('timing_date', sa.Date(), nullable=True),
    sa.Column('timing_period_start', sa.Date(), nullable=True),
    sa.Column('timing_period_end', sa.Date(), nullable=True),
    sa.Column('value_string', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['eob_id'], ['eob.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eob_total',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eob_id', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('category_code', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['eob_id'], ['eob.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eob_item_adjudication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eob_item_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('category_code', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('value_units', sa.Integer(), nullable=True),
    sa.Column('reason_code', sa.String(length=20), nullable=True),
    sa.Column('reason_display', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['eob_item_id'], ['eob_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # ── Denormalized views (recreated idempotently) ──
    op.execute(sa.text(r"""CREATE OR REPLACE VIEW vw_eob AS
 SELECT e.claim_number,
        CASE
            WHEN ((e.payee_ref ~~ 'anthem:Patient:%'::text) OR (en_payee.name ~~* 'member submitted %'::text)) THEN true
            ELSE false
        END AS member_submitted,
    split_part(e.patient_ref, ':'::text, 3) AS patient_id,
    en_patient.name AS patient_name,
    en_prov.name AS provider_name,
    COALESCE(( SELECT string_agg(DISTINCT en_ct.name, ', '::text) AS string_agg
           FROM (eob_care_team ct
             LEFT JOIN entity_names en_ct ON (((en_ct.entity_ref)::text = ct.provider_ref)))
          WHERE (ct.eob_id = e.id)), ''::text) AS care_team_providers,
    en_payee.name AS payee_name,
    e.status,
    e.outcome,
    e.payment_type,
    e.sub_type,
    e.created_date,
    e.claim_received_date,
    e.payment_date,
    e.payment_amount,
        CASE
            WHEN (e.payee_ref ~~ 'anthem:Patient:%'::text) THEN e.payment_amount
            ELSE NULL::double precision
        END AS paid_to_member,
        CASE
            WHEN (e.payee_ref !~~ 'anthem:Patient:%'::text) THEN e.payment_amount
            ELSE NULL::double precision
        END AS paid_to_provider,
    ( SELECT eob_total.amount
           FROM eob_total
          WHERE ((eob_total.eob_id = e.id) AND ((eob_total.category_code)::text = 'submitted'::text))
         LIMIT 1) AS total_submitted,
    ( SELECT eob_total.amount
           FROM eob_total
          WHERE ((eob_total.eob_id = e.id) AND ((eob_total.category_code)::text = 'memberliability'::text))
         LIMIT 1) AS total_member_liability,
    ( SELECT eob_total.amount
           FROM eob_total
          WHERE ((eob_total.eob_id = e.id) AND ((eob_total.category_code)::text = 'benefit'::text))
         LIMIT 1) AS total_benefit,
    ( SELECT eob_total.amount
           FROM eob_total
          WHERE ((eob_total.eob_id = e.id) AND ((eob_total.category_code)::text = 'deductible'::text))
         LIMIT 1) AS total_deductible,
    ( SELECT eob_total.amount
           FROM eob_total
          WHERE ((eob_total.eob_id = e.id) AND ((eob_total.category_code)::text = 'paidtoprovider'::text))
         LIMIT 1) AS total_paid,
    e.submission_origin,
    e.is_out_of_network,
    i.sequence AS item_seq,
    i.hcpcs_code,
    i.hcpcs_display,
    i.modifier_codes,
    i.serviced_date,
    i.serviced_period_start,
    i.serviced_period_end,
    i.location_code,
    i.location_display,
    i.quantity,
    i.submitted_amount,
    i.net_amount,
    i.allowed_amount,
    i.paid_provider,
    i.paid_patient,
    i.deductible AS item_deductible,
    i.coinsurance AS item_coinsurance,
    i.copay AS item_copay,
    i.noncovered AS item_noncovered,
    i.discount AS item_discount,
    i.member_liability,
    i.payment_status,
    i.adjustment_reason,
    COALESCE(( SELECT string_agg((eob_diagnosis.icd_code)::text, ', '::text) AS string_agg
           FROM eob_diagnosis
          WHERE (eob_diagnosis.eob_id = e.id)), ''::text) AS icd_codes,
    COALESCE(( SELECT string_agg(eob_diagnosis.icd_display, ' | '::text) AS string_agg
           FROM eob_diagnosis
          WHERE (eob_diagnosis.eob_id = e.id)), ''::text) AS icd_displays,
    clm_x.claim_status,
    clm_x.claim_created_date,
    clm_x.claim_total_amount,
    e.last_updated
   FROM (((((((eob e
     LEFT JOIN eob_item i ON ((i.eob_id = e.id)))
     LEFT JOIN oauth_tokens ot ON (((ot.patient_id)::text = split_part(e.patient_ref, ':'::text, 3))))
     LEFT JOIN patients p ON ((((p.entity_ref)::text = e.patient_ref) AND ((p.provider)::text = (ot.provider)::text))))
     LEFT JOIN entity_names en_patient ON (((en_patient.entity_ref)::text = (p.entity_ref)::text)))
     LEFT JOIN entity_names en_prov ON (((en_prov.entity_ref)::text = e.provider_ref)))
     LEFT JOIN entity_names en_payee ON (((en_payee.entity_ref)::text = e.payee_ref)))
     LEFT JOIN LATERAL ( SELECT c.status AS claim_status,
            c.created_date AS claim_created_date,
            c.total_amount AS claim_total_amount
           FROM claim_submission c
          WHERE (c.claim_number = e.claim_number)
          ORDER BY (c.status = 'cancelled'::text), c.created_date DESC
         LIMIT 1) clm_x ON (true));"""))
    op.execute(sa.text(r"""CREATE OR REPLACE VIEW vw_claims AS
 SELECT c.claim_number,
    c.claim_adjustment_key,
        CASE
            WHEN ((c.payee_ref ~~ 'anthem:Patient:%'::text) OR (en_payee.name ~~* 'member submitted %'::text)) THEN true
            ELSE false
        END AS member_submitted,
    split_part(c.patient_ref, ':'::text, 3) AS patient_id,
    en_patient.name AS patient_name,
    en_prov.name AS provider_name,
    COALESCE(( SELECT string_agg(DISTINCT en_ct.name, ', '::text) AS string_agg
           FROM (claim_care_team ct
             LEFT JOIN entity_names en_ct ON (((en_ct.entity_ref)::text = ct.provider_ref)))
          WHERE (ct.claim_id = c.id)), ''::text) AS care_team_providers,
    en_payee.name AS payee_name,
    en_ins.name AS insurer_name,
    c.status,
    c.line_status_display,
    c.denial_reason_code,
    c.adjudication_status_code,
    c.action_type_code,
    c.created_date,
    ( SELECT min(e2.claim_received_date) AS min
           FROM eob e2
          WHERE (e2.claim_number = c.claim_number)) AS claim_received_date,
    c.adjudication_date,
    c.action_date,
    c.paid_date,
    c.billable_period_start,
    c.billable_period_end,
    c.total_amount,
    c.payee_type,
    c.submission_origin,
    c.is_out_of_network,
    c.adjustment_number,
    c.document_control_number,
    i.sequence AS item_seq,
    i.quantity,
    i.unit_price,
    i.net_amount,
    i.hcpcs_code,
    i.hcpcs_display,
    i.modifier_codes,
    i.serviced_date,
    i.serviced_period_start,
    i.serviced_period_end,
    i.location_code,
    i.location_display,
    COALESCE(( SELECT string_agg((claim_diagnosis.icd_code)::text, ', '::text) AS string_agg
           FROM claim_diagnosis
          WHERE (claim_diagnosis.claim_id = c.id)), ''::text) AS icd_codes,
    COALESCE(( SELECT string_agg(claim_diagnosis.icd_display, ' | '::text) AS string_agg
           FROM claim_diagnosis
          WHERE (claim_diagnosis.claim_id = c.id)), ''::text) AS icd_displays,
    eob_x.eob_status,
    eob_x.eob_outcome,
    eob_x.eob_disposition,
    eob_x.eob_payment_amount,
    eob_x.eob_created_date,
    c.last_updated
   FROM ((((((((claim_submission c
     LEFT JOIN claim_item i ON ((i.claim_id = c.id)))
     LEFT JOIN oauth_tokens ot ON (((ot.patient_id)::text = split_part(c.patient_ref, ':'::text, 3))))
     LEFT JOIN patients p ON ((((p.entity_ref)::text = c.patient_ref) AND ((p.provider)::text = (ot.provider)::text))))
     LEFT JOIN entity_names en_patient ON (((en_patient.entity_ref)::text = (p.entity_ref)::text)))
     LEFT JOIN entity_names en_prov ON (((en_prov.entity_ref)::text = c.provider_ref)))
     LEFT JOIN entity_names en_ins ON (((en_ins.entity_ref)::text = c.insurer_ref)))
     LEFT JOIN entity_names en_payee ON (((en_payee.entity_ref)::text = c.payee_ref)))
     LEFT JOIN LATERAL ( SELECT e.status AS eob_status,
            e.outcome AS eob_outcome,
            e.disposition AS eob_disposition,
            e.payment_amount AS eob_payment_amount,
            e.created_date AS eob_created_date
           FROM eob e
          WHERE (e.claim_number = c.claim_number)
          ORDER BY (e.status = 'cancelled'::text), e.created_date DESC
         LIMIT 1) eob_x ON (true));"""))
    op.execute(sa.text(r"""CREATE OR REPLACE VIEW vw_member_submitted AS
 SELECT e.id AS eob_id,
    e.claim_number,
    e.status,
    e.submission_origin,
    e.is_out_of_network,
    i.submitted_amount,
    i.allowed_amount,
    i.paid_provider,
    i.paid_patient,
    i.member_liability,
    i.noncovered AS item_noncovered,
    i.deductible AS item_deductible,
    i.coinsurance AS item_coinsurance,
    i.copay AS item_copay,
    i.discount AS item_discount,
    i.sequence AS item_seq,
    i.hcpcs_code,
    i.hcpcs_display,
    i.modifier_codes,
    i.quantity,
    i.serviced_date,
    COALESCE(( SELECT string_agg((d.icd_code)::text, ', '::text) AS string_agg
           FROM eob_diagnosis d
          WHERE (d.eob_id = e.id)), ''::text) AS icd_codes,
    COALESCE(( SELECT string_agg(d.icd_display, ' | '::text) AS string_agg
           FROM eob_diagnosis d
          WHERE (d.eob_id = e.id)), ''::text) AS icd_displays,
    i.payment_status,
    i.adjustment_reason,
    en_prov.name AS provider_name,
    en_payee.name AS payee_name,
    COALESCE(( SELECT string_agg(en_ct.name, ', '::text) AS string_agg
           FROM (eob_care_team ct
             LEFT JOIN entity_names en_ct ON (((en_ct.entity_ref)::text = ct.provider_ref)))
          WHERE (ct.eob_id = e.id)), ''::text) AS care_team_providers,
    COALESCE(( SELECT string_agg(ct.role_display, ', '::text) AS string_agg
           FROM eob_care_team ct
          WHERE (ct.eob_id = e.id)), ''::text) AS care_team_roles,
    split_part(e.patient_ref, ':'::text, 3) AS patient_id,
    en_patient.name AS patient_name,
    e.created_date,
    e.billable_period_start,
    e.billable_period_end,
    ( SELECT eob_total.amount
           FROM eob_total
          WHERE ((eob_total.eob_id = e.id) AND ((eob_total.category_code)::text = 'submitted'::text))
         LIMIT 1) AS total_submitted,
    ( SELECT eob_total.amount
           FROM eob_total
          WHERE ((eob_total.eob_id = e.id) AND ((eob_total.category_code)::text = 'benefit'::text))
         LIMIT 1) AS total_benefit,
    ( SELECT eob_total.amount
           FROM eob_total
          WHERE ((eob_total.eob_id = e.id) AND ((eob_total.category_code)::text = 'deductible'::text))
         LIMIT 1) AS total_deductible,
    ( SELECT eob_total.amount
           FROM eob_total
          WHERE ((eob_total.eob_id = e.id) AND ((eob_total.category_code)::text = 'coinsurance'::text))
         LIMIT 1) AS total_coinsurance,
    ( SELECT sum(eob_item.member_liability) AS sum
           FROM eob_item
          WHERE (eob_item.eob_id = e.id)) AS total_member_liability,
    ( SELECT sum(eob_item.noncovered) AS sum
           FROM eob_item
          WHERE (eob_item.eob_id = e.id)) AS total_noncovered,
    array_to_string(array_remove(ARRAY[
        CASE
            WHEN ((e.submission_origin)::text = 'member'::text) THEN 'origin'::text
            ELSE NULL::text
        END,
        CASE
            WHEN (lower(COALESCE(en_prov.name, ''::text)) ~~ '%member%'::text) THEN 'provider_name'::text
            ELSE NULL::text
        END,
        CASE
            WHEN (lower(COALESCE(en_payee.name, ''::text)) ~~ '%member%'::text) THEN 'payee_name'::text
            ELSE NULL::text
        END,
        CASE
            WHEN (EXISTS ( SELECT 1
               FROM (eob_care_team ct
                 LEFT JOIN entity_names en_ct ON (((en_ct.entity_ref)::text = ct.provider_ref)))
              WHERE ((ct.eob_id = e.id) AND ((lower(COALESCE(en_ct.name, ''::text)) ~~ '%member%'::text) OR (lower((COALESCE(ct.role_code, ''::character varying))::text) ~~ '%member%'::text) OR (lower(COALESCE(ct.role_display, ''::text)) ~~ '%member%'::text))))) THEN 'care_team'::text
            ELSE NULL::text
        END], NULL::text), ';'::text) AS member_signals
   FROM ((((((eob e
     JOIN eob_item i ON ((i.eob_id = e.id)))
     LEFT JOIN oauth_tokens ot ON (((ot.patient_id)::text = split_part(e.patient_ref, ':'::text, 3))))
     LEFT JOIN patients p ON ((((p.entity_ref)::text = e.patient_ref) AND ((p.provider)::text = (ot.provider)::text))))
     LEFT JOIN entity_names en_patient ON (((en_patient.entity_ref)::text = (p.entity_ref)::text)))
     LEFT JOIN entity_names en_prov ON (((en_prov.entity_ref)::text = e.provider_ref)))
     LEFT JOIN entity_names en_payee ON (((en_payee.entity_ref)::text = e.payee_ref)))
  WHERE (((e.submission_origin)::text = 'member'::text) OR (lower(COALESCE(en_prov.name, ''::text)) ~~ '%member%'::text) OR (lower(COALESCE(en_payee.name, ''::text)) ~~ '%member%'::text) OR (EXISTS ( SELECT 1
           FROM (eob_care_team ct
             LEFT JOIN entity_names en_ct ON (((en_ct.entity_ref)::text = ct.provider_ref)))
          WHERE ((ct.eob_id = e.id) AND ((lower(COALESCE(en_ct.name, ''::text)) ~~ '%member%'::text) OR (lower((COALESCE(ct.role_code, ''::character varying))::text) ~~ '%member%'::text) OR (lower(COALESCE(ct.role_display, ''::text)) ~~ '%member%'::text))))));"""))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eob_item_adjudication')
    op.drop_table('eob_total')
    op.drop_table('eob_supporting_info')
    op.drop_table('eob_procedure')
    op.drop_table('eob_item')
    op.drop_table('eob_identifier')
    op.drop_table('eob_diagnosis')
    op.drop_table('eob_care_team')
    op.drop_table('eob_adjudication')
    op.drop_table('claim_item')
    op.drop_table('claim_identifier')
    op.drop_table('claim_diagnosis')
    op.drop_table('claim_care_team')
    op.drop_table('patients')
    op.drop_table('oauth_tokens')
    op.drop_table('member_claim_submission')
    op.drop_table('eob')
    op.drop_table('entity_names')
    op.drop_table('claim_submission')
    op.execute(sa.text('DROP VIEW IF EXISTS vw_eob'))
    op.execute(sa.text('DROP VIEW IF EXISTS vw_claims'))
    op.execute(sa.text('DROP VIEW IF EXISTS vw_member_submitted'))
    # ### end Alembic commands ###
