services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    restart: unless-stopped
    ports:
      - "3999:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dockhand_data:/app/data
      - /mnt/data/docker:/mnt/data/docker
      - /home/maradmin/.ssh:/.ssh:ro
    labels:
        - "wud.watch.digest=true"
        # - "homepage.group=System"
        # - "homepage.id=dockhand-card"
        # - "homepage.name=Dockhand"
        # - "homepage.icon=dockhand.png"
        # - "homepage.href=http://192.168.254.111:3999"
        # - "homepage.target=_self"

volumes:
  dockhand_data:
