[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  flush_interval = "10s"
  hostname = "marserver"

[[outputs.influxdb_v2]]
  urls = ["http://localhost:8087"]
  token = "${INFLUXDB_TOKEN}"
  organization = "home"
  bucket = "telemetry"

[[outputs.influxdb]]
  urls = ["http://192.168.254.22:8086"]
  database = "telemetry"
  username = "${HAOS_INFLUXDB_USER}"
  password = "${HAOS_INFLUXDB_PASSWORD}"

[[inputs.cpu]]
  percpu = true
  totalcpu = true

[[inputs.mem]]

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs"]

[[inputs.sensors]]

[[inputs.nvidia_smi]]
  bin_path = "/usr/bin/nvidia-smi"
